taskset -c 60-90 python run.py  --method gpt2-small --dataset imdb --class_names_file ./default_class_names/review.txt --split_ratio 0.7 --class_names --train_size 0.2 --test_size 0.2 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/review.txt
taskset -c 60-90 python run.py  --method gpt2-medium --dataset imdb --class_names_file ./default_class_names/review.txt --split_ratio 0.7 --class_names --train_size 0.2 --test_size 0.2 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/review.txt

taskset -c 60-90 python run.py  --method gpt2-small --dataset yelp_polarity --class_names_file ./default_class_names/review.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/review.txt
taskset -c 60-90 python run.py  --method gpt2-medium --dataset yelp_polarity --class_names_file ./default_class_names/review.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/review.txt

taskset -c 60-90 python run.py  --method gpt2-small --dataset yelp_review_full --class_names_file ./default_class_names/review_5.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/review.txt
taskset -c 60-90 python run.py  --method gpt2-medium --dataset yelp_review_full --class_names_file ./default_class_names/review_5.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/review.txt

taskset -c 60-90 python run.py  --method gpt2-small --dataset NYT-Locations --class_names_file ./default_class_names/nyt-loc.txt --split_ratio 0.8 --class_names --train_size 0.2 --test_size 1 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/loc.txt
taskset -c 60-90 python run.py  --method gpt2-medium --dataset NYT-Locations --class_names_file ./default_class_names/nyt-loc.txt --split_ratio 0.8 --class_names --train_size 0.2 --test_size 1 --gpu 5 --suffix "--iter 100 --dcpmi" --additional_method ProtoCal --prompt --prompt_file ./prompts/loc.txt
