taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/1.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100"
taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/2.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100"
taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/3.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100"
taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/4.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100"

taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/1.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/2.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/3.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method gpt2-medium --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/nyt/4.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu 7 --prompt --suffix "--iter 100" --additional_method ProtoCal
