gpu=$1

taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News --class_names_file ./default_class_names/20.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bbc --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset NYT --class_names_file ./default_class_names/nyt.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bbc --add_mask"


taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bbc --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type blc --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-base --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-large --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bart-base --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bart-large --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type electra-base --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type electra-large --add_mask"


taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bbc --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type blc --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-base --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-large --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bart-base --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset 20News-fine --class_names_file ./default_class_names/20-fine.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --prompt --suffix "--lm_type bart-large --add_mask" --additional_method ProtoCal
