gpu=$1
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type bbc --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type blc --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-base --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-large --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type bart-base --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type bart-large --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type electra --add_mask"
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type electra --add_mask"


taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type bbc --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type blc --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-base --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type roberta-large --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type bart-base --add_mask" --additional_method ProtoCal
taskset -c 30-60 python run.py  --method BERTprompt --dataset dbpedia_14 --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --prompt --suffix "--lm_type bart-large --add_mask" --additional_method ProtoCal
