gpu=$1
taskset -c 30-60 python run.py  --method LOTClass --dataset ag_news --class_names_file ./default_class_names/ag.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.05 --test_size 1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10"
taskset -c 30-60 python run.py  --method LOTClass --dataset ag_news --class_names_file ./default_class_names/ag.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.05 --test_size 1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10 --pretrained_lm bert-large-uncased"

taskset -c 30-60 python run.py --method LOTClass --dataset yelp_polarity --class_names_file ./default_class_names/review.txt --prompt_file ./prompts/review.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10"
taskset -c 30-60 python run.py --method LOTClass --dataset yelp_polarity --class_names_file ./default_class_names/review.txt --prompt_file ./prompts/review.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10 --pretrained_lm bert-large-uncased"

taskset -c 30-60 python run.py --method LOTClass --dataset dbpedia_14 --text_name title content --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10"
taskset -c 30-60 python run.py --method LOTClass --dataset dbpedia_14 --text_name title content --class_names_file ./default_class_names/dbpedia.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.01 --test_size 0.1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10 --pretrained_lm bert-large-uncased"

taskset -c 30-60 python run.py --method LOTClass --dataset 20News --class_names_file ./default_class_names/20.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10"
taskset -c 30-60 python run.py --method LOTClass --dataset 20News --class_names_file ./default_class_names/20.txt --prompt_file ./prompts/topic.txt --split_ratio 0.7 --class_names --train_size 0.5 --test_size 1 --gpu ${gpu} --suffix "--top_pred_num 100 --match_threshold 10 --pretrained_lm bert-large-uncased"